stages:
    - pre-build
    - test
    - build

lint_python:
    stage: pre-build
    image: python:latest
    script:
        - pip install flake8
        - make lint

tests:
    stage: test
    image: python:latest
    script:
        - make pip-install
        - make test

build_docker:
    stage: build
    script:
        - make docker-build
