services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
    - pre-build
    - test
    - build

lint_python:
    stage: pre-build
    image: python:latest
    before_script:
        - pip install flake8
    script:
        - make lint

tests:
    stage: test
    image: python:latest
    before_script:
        - make pip-install
    script:
        - make test

build_docker:
    stage: build
    image: docker:latest
    before_script:
        - apt install build-essential
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - make docker-build
