image: docker:latest

services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay
    SECRET_PATH: ./my_site/settings/secret_settings.py

stages:
    - pre-build
    - test
    - build

lint_python:
    stage: pre-build
    image: python:latest
    before_script:
        - pipenv install flake8
    script:
        - make lint
    tags:
        - shared

tests:
    stage: test
    image: python:latest
    before_script:
        - make pipenv-install
    script:
        - make test
    tags:
        - shared

build_docker:
    stage: build
    before_script:
        - echo SECRET_KEY = \'$SECRET_KEY\' > $SECRET_PATH
        - apk update && apk add make
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - make docker-build
    tags:
        - docker
