stages:
    - pre-build
    - test

lint-python:
    stage: pre-build
    image: python:3.6.1
    script:
        - pip install flake8
        - make lint

tests:
    stage: test
    image: python:3.6.1
    script:
        - env | grep SECRET_KEY
        - make install-requirements
        - make test
