# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170804_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('Category',), 'verbose_name_plural': ('Categories',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': ('Post',), 'verbose_name_plural': ('Posts',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
    ]
