# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170831_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
    ]
