# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170906_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview_image_height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preview_image_width',
        ),
    ]
