# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:15
from __future__ import unicode_literals

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170906_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
