# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 08:03
from __future__ import unicode_literals

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170926_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=martor.models.MartorField(default=''),
        ),
    ]
