# Generated by Django 2.0.2 on 2018-03-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180304_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='updated_date',
        ),
    ]
