# Generated by Django 2.0.2 on 2018-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180304_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'published')], default=0),
        ),
    ]
