# Generated by Django 2.0.2 on 2018-03-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_userstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='session',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
