# Generated by Django 2.0.2 on 2018-03-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180327_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistic',
            name='session',
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='cookie',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
